version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:5001}
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
